(ns euler.p2)

; Each new term in the Fibonacci sequence is generated by adding the previous
; two terms. By starting with 1 and 2, the first 10 terms will be:
;
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; By considering the terms in the Fibonacci sequence whose values do not exceed
; four million, find the sum of the even-valued terms.


(def start-nums [1 2])
(def fib-seq
  (lazy-cat start-nums (map + (rest fib-seq) fib-seq)))

(def up-to 4000000)
(->> (take-while #(< % up-to) fib-seq)
     (filter even?)
     (apply +))

; 4613732